### ISSUE TITLE
Error: java.lang.NoSuchMethodError - with version moreoverlays-1.24.1-mc1.21.9-neoforge

### ISSUE THREAD

**Issue by SkipperFabi** [r8420/MoreOverlays-updated#80]
Hey, just tried to use your 1.21.9 neoforge version, unfortunetly it keeps crashing.
Modloader: Neoforge
Modloader version: neoforge - 21.9.16
Mod version: moreoverlays-1.24.1-mc1.21.9-neoforge.jar

When pressing any key f.e. F7 or F9 to open the Overlays minecraft crashes (in singleplayer and multiplayer) with following error:
-----------------------------------------------------------------------------------------------------------
The game crashed: unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.client.renderer.state.CameraRenderState net.neoforged.neoforge.client.event.RenderLevelStageEvent$AfterEntities.getCamera()'
-----------------------------------------------------------------------------------------------------------

For the detailed log see: https://mclo.gs/Z9eU2Ow (if you wish i can copy/paste it in the issue aswell)

I deactivated all other mods aswell, pretty sure it's not another mod causing this.

Also tried it with an older modloader, which caused the same issue.

Thanks in advance :)

**Comment by SkipperFabi** [comment]
Fixed with using an older modloader version. Sorry! Works with modloader version: neoforge - 21.9.12 (and prob below - haven't tested that)
